version: "3.8"

services:
  moxie_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/
    ports:
      - 8888:8000
    env_file:
      - ./.env
    container_name: moxie_api
    depends_on:
      - moxie_db

  moxie_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    env_file:
      - ./.env
    container_name: moxie_db

volumes:
  postgres_data:
